language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script: coverage run setup.py test
after_success:
  - codecov
matrix:
  allow_failures:
    # Travis CI is having trouble building these versions of Python right now.
    # https://github.com/travis-ci/travis-ci/issues/9069
    - python: "3.7"
    - python: "3.8-dev"
    - python: "nightly"
